### PR TITLE
jsonschemas: update licenses schema fields

### PR DESCRIPTION
**Pull request by ChiaraBi**

### CODE REVIEW

**Comment by egabancho** [comment]
Naive question ☺️ since we are naming the schemas `license-v1.0.0.json`, does it make sense to create a new version of the schema with this changes? i.e. `license-v1.0.1.json`

**Comment by slint** [comment]
I would go with the *"this package is still in alpha"* excuse and keep `v1.0.0`... :see_no_evil: 

Also for `v1.0.1` to work (ie. keep compatibility for old documents stored in `RecordMetadata`) we would have to "duplicate" the schema and serve `v1.0.0` as well under the `/schemas` endpoint (or migrate).

Though I guess that someone will have to bite the bullet at some point and tell the story of how painful JSONSchema updates might be :grin:

**Comment by ChiaraBi** [comment]
The build is passing.

**Comment by krzysztof** [comment]
@lnielsen Why are cron builds off for this repo (10 months ago).

**Comment by lnielsen** [comment]
@krzysztof Because when I enabled cronjobs for repositories then Travis was completely blocked.

**Pull request merged**
